/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GTable {
        "minSize": number;
    }
}
declare global {
    interface HTMLGTableElement extends Components.GTable, HTMLStencilElement {
    }
    var HTMLGTableElement: {
        prototype: HTMLGTableElement;
        new (): HTMLGTableElement;
    };
    interface HTMLElementTagNameMap {
        "g-table": HTMLGTableElement;
    }
}
declare namespace LocalJSX {
    interface GTable {
        "minSize"?: number;
    }
    interface IntrinsicElements {
        "g-table": GTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "g-table": LocalJSX.GTable & JSXBase.HTMLAttributes<HTMLGTableElement>;
        }
    }
}
